FROM python:3 
WORKDIR /python-docker
COPY . .
RUN pip install -r ${PWD}/requirement.txt
ENV FLASK_APP=main
CMD ["flask", "run", "--port=5000", "--host=0.0.0.0"]
LABEL org.opencontainers.image.source https://github.com/TsuiSauChi/HyperledgerConcepts