# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
        external-access: external-access
    spec:
      containers:
        - name: example-frontend
          image: jamestsui/example-frontend:latest
          # Set env variable to connect to frontend service
          env:
            - name: BACKEND_ADDRESS
              value: "http://backend-service"
            - name: BACKEND_PORT
              # Points to backend-service
              value: "81"
          ports:
            - name: frontend-port
              containerPort: 5000

---

# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app-service: backend
    spec:
      containers:
        - name: example-backend
          image: jamestsui/example-backend:latest
          # Set env variable to connect to database service
          env:
            - name: DATABASE_ADDRESS
              value: "database-service"
          ports:
            - containerPort: 5000
