# NodePort: For External Access

apiVersion: v1
kind: Service
metadata:
  name: frontend-access
spec:
  type: NodePort
  selector:
    external-access: external-access
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  
---

# ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec: 
  selector:
    app-service: backend
  ports:
    - protocol: TCP 
      port: 81
      targetPort: 5000

---

# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-pod
  ports: 
    - port: 5432
      name: 
  clusterIP: None
