version: "3.9"

services:
  frontend:
    build: ./frontend
    environment:
      BACKEND_ADDRESS: http://backend
      BACKEND_PORT: 5000
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    environment:
      DATABASE_ADDRESS: docker_db_1
    ports: 
      - "8000:5000"
  db:
    image: postgres 
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/docker-entrypoint-initdb.d
