CREATE TABLE IF NOT EXISTS Users (
     id     INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
     name   TEXT,
     age    INTEGER
);

INSERT INTO Users (name, age) VALUES ('James', 24);
INSERT INTO Users (name, age) VALUES ('Potato Man', 20);
